Repository Course-Hero-3/MotivateMe, pull requests merged in 2022-08, with the labels that each got.

#127 Button Fix and Error Check
  motivateme-ui/src/components/ProfilePage/ProfilePage.jsx
  motivateme-ui/src/components/RecapPage/RecapPage.jsx
  motivateme-ui/src/components/RegisterPage/RegisterPage.jsx
Labels: bug, enhancement

#130 Made small tweaks for important visibility changes
  motivateme-ui/src/components/DashboardPage/DashboardPage.jsx
  motivateme-ui/src/components/Navbar/Navbar.css
  motivateme-ui/src/components/Navbar/Navbar.jsx
  motivateme-ui/src/components/RecapPage/RecapPage.jsx
  motivateme-ui/src/components/SocialPage/SocialPage.css
  motivateme-ui/src/components/SocialPage/SocialPage.jsx
  motivateme-ui/src/components/TodoList/TodoList.jsx
  motivateme-ui/src/components/TodoPage/TodoPage.jsx
Labels: bug, enhancement

#133 Collapse empty box
  motivateme-ui/src/components/Navbar/Navbar.css
  motivateme-ui/src/components/RecapPage/RecapPage.css
  motivateme-ui/src/components/SocialPage/SocialPage.css
  motivateme-ui/src/components/SocialPage/SocialPage.jsx
  motivateme-ui/src/components/TodoList/TodoList.css
Labels: enhancement

#132 Added expandable search bars
  motivateme-ui/src/components/Navbar/Navbar.css
  motivateme-ui/src/components/RecapPage/RecapPage.css
  motivateme-ui/src/components/SocialPage/SocialPage.css
  motivateme-ui/src/components/SocialPage/SocialPage.jsx
  motivateme-ui/src/components/TodoList/TodoList.css
Labels: enhancement

#135 Notifications #105
  mm-api/.env
  mm-api/README.md
  mm-api/config.js
  mm-api/models/todo.js
  mm-api/models/user.js
  mm-api/motivateme-schema.sql
  mm-api/package.json
  mm-api/routes/auth.js
  mm-api/routes/todo.js
  mm-api/sendSMS.js
  motivateme-ui/src/components/DashboardPage/DashboardPage.css
  motivateme-ui/src/components/DashboardPage/DashboardPage.jsx
  motivateme-ui/src/components/GraphCard/GraphCard.css
  motivateme-ui/src/components/RegisterPage/RegisterPage.jsx
Labels: enhancement

#137 Overall Enhancement + Fixes
  mm-api/README.md
  mm-api/models/todo.js
  mm-api/models/user.js
  mm-api/motivateme-schema.sql
  mm-api/package.json
  mm-api/routes/auth.js
  motivateme-ui/services/apiclient.js
  motivateme-ui/src/components/DashboardPage/DashboardPage.css
  motivateme-ui/src/components/DashboardPage/DashboardPage.jsx
  motivateme-ui/src/components/LandingPage/LandingPage.css
  motivateme-ui/src/components/LandingPage/LandingPage.jsx
  motivateme-ui/src/components/Navbar/Navbar.css
  motivateme-ui/src/components/ProfilePage/ProfilePage.css
  motivateme-ui/src/components/ProfilePage/ProfilePage.jsx
  motivateme-ui/src/components/RecapPage/RecapPage.css
  motivateme-ui/src/components/RegisterPage/RegisterPage.css
  motivateme-ui/src/components/RegisterPage/RegisterPage.jsx
  motivateme-ui/src/components/SocialPage/SocialPage.css
  motivateme-ui/src/components/TodoList/TodoList.jsx
  motivateme-ui/src/components/TodoPage/TodoPage.css
Labels: bug, enhancement

#141 matched the css on all components
  motivateme-ui/src/components/DashboardPage/DashboardPage.css
  motivateme-ui/src/components/GraphCard/GraphCard.css
  motivateme-ui/src/components/ProfilePage/ProfilePage.css
  motivateme-ui/src/components/SocialPage/SocialPage.css
  motivateme-ui/src/components/TodoList/TodoList.css
Labels: documentation

#143 Image Upload Functionality
  mm-api/config.js
  mm-api/middleware/security.js
  mm-api/models/user.js
  mm-api/routes/auth.js
  mm-api/routes/recap.js
  mm-api/utils/tokens.js
  motivateme-ui/.env
  motivateme-ui/.env.template
  motivateme-ui/.gitignore
  motivateme-ui/README.md
  motivateme-ui/package-lock.json
  motivateme-ui/package.json
  motivateme-ui/src/assets/pencil-icon.png
  motivateme-ui/src/components/App/App.jsx
  motivateme-ui/src/components/ProfilePage/ProfilePage.css
  motivateme-ui/src/components/ProfilePage/ProfilePage.jsx
  motivateme-ui/src/components/RegisterPage/RegisterPage.css
  motivateme-ui/src/components/RegisterPage/RegisterPage.jsx
  motivateme-ui/vite.config.js
Labels: bug, enhancement

#145 Created Endpoint for AWS Config Information
  mm-api/.env
  mm-api/.env.template
  mm-api/models/user.js
  mm-api/routes/auth.js
  motivateme-ui/services/apiclient.js
  motivateme-ui/src/components/ProfilePage/ProfilePage.jsx
  motivateme-ui/src/components/RegisterPage/RegisterPage.jsx
Labels: enhancement

#150 implement basic history section component
  mm-api/models/recap.js
  mm-api/models/todo.js
  mm-api/routes/recap.js
  motivateme-ui/README.md
  motivateme-ui/src/components/DashboardPage/DashboardPage.css
  motivateme-ui/src/components/DashboardPage/DashboardPage.jsx
Labels: enhancement

#148 added darkmode feature
  motivateme-ui/README.md
  motivateme-ui/index.html
  motivateme-ui/package.json
  motivateme-ui/src/assets/Google_Calendar_icon_(2020).svg.png
  motivateme-ui/src/assets/monday-200x200-1.png
  motivateme-ui/src/assets/myhomework logo.png
  motivateme-ui/src/components/App/App.jsx
  motivateme-ui/src/components/DashboardPage/DashboardPage.css
  motivateme-ui/src/components/GraphCard/GraphCard.css
  motivateme-ui/src/components/LandingPage/LandingPage.css
  motivateme-ui/src/components/LoginPage/LoginPage.css
  motivateme-ui/src/components/Navbar/Navbar.css
  motivateme-ui/src/components/ProfilePage/ProfilePage.css
  motivateme-ui/src/components/ProfilePage/ProfilePage.jsx
  motivateme-ui/src/components/RegisterPage/RegisterPage.css
  motivateme-ui/src/components/SocialPage/SocialPage.css
  motivateme-ui/src/components/TodoForm/TodoForm.css
  motivateme-ui/src/components/TodoList/TodoList.css
  motivateme-ui/src/components/TodoList/TodoList.jsx
  motivateme-ui/src/components/theme.jsx
Labels: enhancement

#151 fixed history component
  motivateme-ui/src/components/DashboardPage/DashboardPage.css
Labels: enhancement

#152 Made edits for demo, updated some colors but more need to be edited
  motivateme-ui/package-lock.json
  motivateme-ui/src/components/DashboardPage/DashboardPage.css
  motivateme-ui/src/components/ProfilePage/ProfilePage.css
  motivateme-ui/src/components/RegisterPage/RegisterPage.css
  motivateme-ui/src/components/SocialPage/SocialPage.css
  motivateme-ui/src/components/TodoList/TodoList.css
Labels: bug

#153 Everything is readable now in light and dark mode
  motivateme-ui/src/components/DashboardPage/DashboardPage.css
  motivateme-ui/src/components/DashboardPage/DashboardPage.jsx
  motivateme-ui/src/components/LoginPage/LoginPage.css
  motivateme-ui/src/components/ProfilePage/ProfilePage.css
  motivateme-ui/src/components/RegisterPage/RegisterPage.css
  motivateme-ui/src/components/SocialPage/SocialPage.css
  motivateme-ui/src/components/TodoForm/TodoForm.css
  motivateme-ui/src/components/TodoList/TodoList.css
  motivateme-ui/src/components/TodoList/TodoList.jsx
Labels: bug

#155 Time Zone Fixing
  mm-api/models/todo.js
  motivateme-ui/src/components/DashboardPage/DashboardPage.jsx
  motivateme-ui/src/components/SocialPage/SocialPage.jsx
  motivateme-ui/src/components/TodoForm/TodoForm.jsx
  motivateme-ui/src/components/TodoList/TodoList.jsx
Labels: bug, enhancement

#156 Small images upload
  mm-api/models/todo.js
  mm-api/models/user.js
  motivateme-ui/package-lock.json
  motivateme-ui/package.json
  motivateme-ui/src/components/ProfilePage/ProfilePage.jsx
  motivateme-ui/src/components/RegisterPage/RegisterPage.jsx
Labels: bug, enhancement

#157 Got rid of console log
  mm-api/models/todo.js
Labels: bug, enhancement

#158 Syntax error on error handling
  motivateme-ui/src/components/RegisterPage/RegisterPage.jsx
Labels: bug, enhancement

#159 Got rid of unnecessary variables
  mm-api/middleware/permissions.js
  mm-api/models/todo.js
  motivateme-ui/src/components/App/App.jsx
  motivateme-ui/src/components/LandingPage/LandingPage.jsx
  motivateme-ui/src/components/LoginPage/LoginPage.jsx
  motivateme-ui/src/components/Navbar/Navbar.jsx
  motivateme-ui/src/components/RegisterPage/RegisterPage.jsx
  motivateme-ui/src/components/TodoForm/TodoForm.jsx
  motivateme-ui/src/components/TodoList/TodoList.jsx
Labels: enhancement

#160 Deploy Files
  README.md
  mm-api/.env.template
  mm-api/Procfile
  mm-api/app-DESKTOP-3VNSNOA.js
  mm-api/app.js
  mm-api/config.js
  mm-api/google33fd78c5f6785989.html
  motivateme-ui/CORS
  motivateme-ui/package-lock-DESKTOP-3VNSNOA.json
  motivateme-ui/package.json
  motivateme-ui/services/apiclient.js
  motivateme-ui/static.json
Labels: enhancement

#164 fixed css on hover effect for navlinks
  motivateme-ui/services/apiclient.js
  motivateme-ui/src/components/Navbar/Navbar.css
  motivateme-ui/src/components/Navbar/Navbar.jsx
  motivateme-ui/src/components/RegisterPage/RegisterPage.jsx
Labels: documentation

#165 added text for register page on notifs
  motivateme-ui/src/components/RegisterPage/RegisterPage.jsx
Labels: documentation

#166 Made plenty css upgrades (especially input)
  motivateme-ui/src/components/App/App.jsx
  motivateme-ui/src/components/DoughnutVisual/DoughnutVisual.jsx
  motivateme-ui/src/components/GraphCard/GraphCard.css
  motivateme-ui/src/components/GraphCard/GraphCard.jsx
  motivateme-ui/src/components/LandingPage/LandingPage.css
  motivateme-ui/src/components/LandingPage/LandingPage.jsx
  motivateme-ui/src/components/LoginPage/LoginPage.css
  motivateme-ui/src/components/PieVisual/PieVisual.jsx
  motivateme-ui/src/components/ProfilePage/ProfilePage.css
  motivateme-ui/src/components/ProfilePage/ProfilePage.jsx
  motivateme-ui/src/components/RecapPage/RecapPage.css
  motivateme-ui/src/components/RecapPage/RecapPage.jsx
  motivateme-ui/src/components/RegisterPage/RegisterPage.css
  motivateme-ui/src/components/RegisterPage/RegisterPage.jsx
  motivateme-ui/src/components/SecurityChange/SecurityChange.css
  motivateme-ui/src/components/SocialPage/SocialPage.css
  motivateme-ui/src/components/TodoForm/TodoForm.css
  motivateme-ui/src/components/TodoList/TodoList.css
  motivateme-ui/src/components/TodoList/TodoList.jsx
Labels: bug, enhancement

#170 made task cards responsive
  motivateme-ui/src/components/TodoList/TodoList.css
  motivateme-ui/src/components/TodoList/TodoList.jsx
Labels: enhancement

#171 Fixed graphs on dashboard, todo dropdowns, landing cards
  motivateme-ui/src/components/GraphCard/GraphCard.css
  motivateme-ui/src/components/LandingPage/LandingPage.css
  motivateme-ui/src/components/LandingPage/LandingPage.jsx
  motivateme-ui/src/components/TodoForm/TodoForm.css
  motivateme-ui/src/components/TodoForm/TodoForm.jsx
  motivateme-ui/src/components/TodoList/TodoList.jsx
Labels: enhancement

#173 Modal responsive update #172
  motivateme-ui/services/apiclient.js
  motivateme-ui/src/components/TodoForm/TodoForm.css
  motivateme-ui/src/components/TodoForm/TodoForm.jsx
  motivateme-ui/src/components/TodoList/TodoList.css
  motivateme-ui/src/components/TodoList/TodoList.jsx
Labels: enhancement

#177 Fixed and enhanced some pages
  motivateme-ui/services/apiclient.js
  motivateme-ui/src/components/App/App.jsx
  motivateme-ui/src/components/DashboardPage/DashboardPage.css
  motivateme-ui/src/components/DashboardPage/DashboardPage.jsx
  motivateme-ui/src/components/Navbar/Navbar.css
  motivateme-ui/src/components/ProfilePage/ProfilePage.css
  motivateme-ui/src/components/TodoList/TodoList.css
  motivateme-ui/src/components/TodoList/TodoList.jsx
  motivateme-ui/src/index.css
Labels: bug, enhancement

#178 Added followers, switch, fixed inputs, fixed refresh dark/light mode
  README.md
  mm-api/models/recap.js
  mm-api/models/social.js
  motivateme-ui/package-lock.json
  motivateme-ui/src/components/App/App.jsx
  motivateme-ui/src/components/DashboardPage/DashboardPage.jsx
  motivateme-ui/src/components/LoginPage/LoginPage.jsx
  motivateme-ui/src/components/Navbar/Navbar.css
  motivateme-ui/src/components/ProfilePage/ProfilePage.css
  motivateme-ui/src/components/ProfilePage/ProfilePage.jsx
  motivateme-ui/src/components/RecapPage/RecapPage.jsx
  motivateme-ui/src/components/RegisterPage/RegisterPage.jsx
  motivateme-ui/src/components/SocialPage/SocialPage.css
  motivateme-ui/src/components/SocialPage/SocialPage.jsx
  motivateme-ui/src/components/TodoList/TodoList.jsx
Labels: documentation, enhancement

#184 Clear image, max/min cap, landing card box shadow
  motivateme-ui/src/components/LandingPage/LandingPage.css
  motivateme-ui/src/components/RegisterPage/RegisterPage.css
  motivateme-ui/src/components/RegisterPage/RegisterPage.jsx
  motivateme-ui/src/components/TodoList/TodoList.jsx
Labels: enhancement

#185 added text on registerpage, complete modal, and create modal
  motivateme-ui/src/components/RegisterPage/RegisterPage.css
  motivateme-ui/src/components/RegisterPage/RegisterPage.jsx
  motivateme-ui/src/components/TodoForm/TodoForm.css
  motivateme-ui/src/components/TodoForm/TodoForm.jsx
Labels: documentation

#187 adjusted css for dark mode in todo and dashboard
  motivateme-ui/src/components/DashboardPage/DashboardPage.css
  motivateme-ui/src/components/DashboardPage/DashboardPage.jsx
  motivateme-ui/src/components/TodoList/TodoList.css
  motivateme-ui/src/components/TodoList/TodoList.jsx
  motivateme-ui/src/index.css
Labels: documentation

#188 made social page responsive
  motivateme-ui/src/components/App/App.jsx
  motivateme-ui/src/components/Navbar/Navbar.css
  motivateme-ui/src/components/Navbar/Navbar.jsx
  motivateme-ui/src/components/ProfilePage/ProfilePage.jsx
  motivateme-ui/src/components/SocialPage/SocialPage.css
  motivateme-ui/src/components/SocialPage/SocialPage.jsx
Labels: enhancement

#189 Dashboard responsiveness
  motivateme-ui/src/components/BarVisual/BarVisual.jsx
  motivateme-ui/src/components/DashboardPage/DashboardPage.css
  motivateme-ui/src/components/DoubleBarVisual/DoubleBarVisual.jsx
  motivateme-ui/src/components/HorizontalBarVisual/HorizontalBarVisual.jsx
  motivateme-ui/src/components/LineVisual/LineVisual.jsx
  motivateme-ui/src/components/SocialPage/SocialPage.css
Labels: enhancement

#191 Width of names, fixed switch
  motivateme-ui/src/components/DashboardPage/DashboardPage.css
  motivateme-ui/src/components/ProfilePage/ProfilePage.jsx
Labels: enhancement

#192 FIxed phone browser issues (create/update Date objects)
  motivateme-ui/src/components/TodoForm/TodoForm.jsx
  motivateme-ui/src/components/TodoList/TodoList.jsx
Labels: bug, enhancement

#194 changes icons on todo component
  motivateme-ui/src/components/TodoList/TodoList.css
  motivateme-ui/src/components/TodoList/TodoList.jsx
Labels: documentation

#195 Fixed colors, icons, sizing in dark mode
  motivateme-ui/src/components/DashboardPage/DashboardPage.css
  motivateme-ui/src/components/DashboardPage/DashboardPage.jsx
  motivateme-ui/src/components/SocialPage/SocialPage.css
  motivateme-ui/src/components/TodoForm/TodoForm.css
  motivateme-ui/src/components/TodoForm/TodoForm.jsx
  motivateme-ui/src/components/TodoList/TodoList.css
  motivateme-ui/src/components/TodoList/TodoList.jsx
  motivateme-ui/src/components/TodoPage/TodoPage.css
Labels: enhancement

#196 added darkmode changes dashboard and fixed pfp sizing
  motivateme-ui/src/components/DashboardPage/DashboardPage.css
  motivateme-ui/src/components/DashboardPage/DashboardPage.jsx
  motivateme-ui/src/components/Navbar/Navbar.css
  motivateme-ui/src/components/ProfilePage/ProfilePage.css
Labels: documentation

#197 Small improvements everywhere
  motivateme-ui/src/components/AccessForbidden/AccessForbidden.css
  motivateme-ui/src/components/AccessForbidden/AccessForbidden.jsx
  motivateme-ui/src/components/BarVisual/BarVisual.jsx
  motivateme-ui/src/components/DashboardPage/DashboardPage.css
  motivateme-ui/src/components/DashboardPage/DashboardPage.jsx
  motivateme-ui/src/components/DoubleBarVisual/DoubleBarVisual.jsx
  motivateme-ui/src/components/DoughnutVisual/DoughnutVisual.jsx
  motivateme-ui/src/components/GraphCard/GraphCard.jsx
  motivateme-ui/src/components/HorizontalBarVisual/HorizontalBarVisual.jsx
  motivateme-ui/src/components/LandingPage/LandingPage.css
  motivateme-ui/src/components/LandingPage/LandingPage.jsx
  motivateme-ui/src/components/LineVisual/LineVisual.jsx
  motivateme-ui/src/components/Navbar/Navbar.css
  motivateme-ui/src/components/Navbar/Navbar.jsx
  motivateme-ui/src/components/PieVisual/PieVisual.jsx
  motivateme-ui/src/components/ProfilePage/ProfilePage.jsx
  motivateme-ui/src/components/SocialPage/SocialPage.css
  motivateme-ui/src/components/SocialPage/SocialPage.jsx
  motivateme-ui/src/components/TodoForm/TodoForm.jsx
  motivateme-ui/src/components/TodoList/TodoList.jsx
Labels: enhancement

#201 Darkmode fix
  motivateme-ui/src/components/App/App.jsx
  motivateme-ui/src/components/DashboardPage/DashboardPage.css
  motivateme-ui/src/components/DashboardPage/DashboardPage.jsx
  motivateme-ui/src/components/GraphCard/GraphCard.css
  motivateme-ui/src/components/GraphCard/GraphCard.jsx
  motivateme-ui/src/components/LandingPage/LandingPage.css
  motivateme-ui/src/components/LoginPage/LoginPage.css
  motivateme-ui/src/components/LoginPage/LoginPage.jsx
  motivateme-ui/src/components/Navbar/Navbar.css
  motivateme-ui/src/components/Navbar/Navbar.jsx
  motivateme-ui/src/components/ProfilePage/ProfilePage.css
  motivateme-ui/src/components/RecapPage/RecapPage.css
  motivateme-ui/src/components/RegisterPage/RegisterPage.css
  motivateme-ui/src/components/SocialPage/SocialPage.css
  motivateme-ui/src/components/TodoForm/TodoForm.css
  motivateme-ui/src/components/TodoForm/TodoForm.jsx
  motivateme-ui/src/components/TodoList/TodoList.css
  motivateme-ui/src/components/TodoList/TodoList.jsx
  motivateme-ui/src/components/theme.jsx
  motivateme-ui/src/index.css
Labels: enhancement

#202 FINAL PR before demo day
  motivateme-ui/services/apiclient.js
  motivateme-ui/src/components/LandingPage/LandingPage.css
  motivateme-ui/src/components/LandingPage/LandingPage.jsx
  motivateme-ui/src/components/ProfilePage/ProfilePage.css
  motivateme-ui/src/components/ProfilePage/ProfilePage.jsx
  motivateme-ui/src/components/RecapPage/RecapPage.jsx
  motivateme-ui/src/components/SecurityChange/SecurityChange.css
  motivateme-ui/src/components/SocialPage/SocialPage.css
  motivateme-ui/src/components/SocialPage/SocialPage.jsx
Labels: enhancement
