Repository Course-Hero-3/MotivateMe, pull requests merged in 2022-07, with the labels that each got.

#63 Updated and added graphs/statistics
  mm-api/models/recap.js
  motivateme-ui/src/components/BarVisual/BarVisual.jsx
  motivateme-ui/src/components/HorizontalBarVisual/HorizontalBarVisual.jsx
  motivateme-ui/src/components/LineVisual/LineVisual.jsx
  motivateme-ui/src/components/RecapPage/RecapPage.css
  motivateme-ui/src/components/RecapPage/RecapPage.jsx
Labels: enhancement

#65 completed the accessforbidden/notfound components
  motivateme-ui/src/components/AccessForbidden/AccessForbidden.css
  motivateme-ui/src/components/AccessForbidden/AccessForbidden.jsx
  motivateme-ui/src/components/App/App.jsx
  motivateme-ui/src/components/NotFound/NotFound.css
  motivateme-ui/src/components/NotFound/NotFound.jsx
Labels: enhancement

#68 Added basics to dashboard, separated concerns for graphs
  motivateme-ui/src/components/App/App.jsx
  motivateme-ui/src/components/DashboardPage/DashboardPage.css
  motivateme-ui/src/components/DashboardPage/DashboardPage.jsx
  motivateme-ui/src/components/GraphCard/GraphCard.css
  motivateme-ui/src/components/GraphCard/GraphCard.jsx
  motivateme-ui/src/components/RecapPage/RecapPage.css
  motivateme-ui/src/components/RecapPage/RecapPage.jsx
Labels: enhancement

#72 Fixed error checking bugs related to login, register, backend (emails)
  mm-api/README.md
  mm-api/models/user.js
  mm-api/package.json
  motivateme-ui/src/components/LoginPage/LoginPage.jsx
  motivateme-ui/src/components/RegisterPage/RegisterPage.jsx
Labels: bug

#77 fixed todo card bug
  motivateme-ui/src/components/TodoList/TodoList.jsx
Labels: bug

#80 Fixed refresh issues and logo redirection if user logged in
  motivateme-ui/src/components/DashboardPage/DashboardPage.jsx
  motivateme-ui/src/components/Navbar/Navbar.jsx
  motivateme-ui/src/components/RecapPage/RecapPage.jsx
  motivateme-ui/src/components/TodoPage/TodoPage.jsx
Labels: bug

#84 Social backend
  mm-api/app.js
  mm-api/models/recap.js
  mm-api/models/social.js
  mm-api/models/todo.js
  mm-api/routes/social.js
Labels: enhancement

#86 finished skeleton for social
  motivateme-ui/src/components/App/App.jsx
  motivateme-ui/src/components/Navbar/Navbar.jsx
  motivateme-ui/src/components/SocialPage/SocialPage.css
  motivateme-ui/src/components/SocialPage/SocialPage.jsx
Labels: enhancement

#87 Fixed access forbidden.
  motivateme-ui/src/components/App/App.jsx
  motivateme-ui/src/components/Navbar/Navbar.css
  motivateme-ui/src/components/Navbar/Navbar.jsx
  motivateme-ui/src/components/RecapPage/RecapPage.jsx
  motivateme-ui/src/components/SocialPage/SocialPage.jsx
  motivateme-ui/src/components/TodoPage/TodoPage.jsx
Labels: bug

#90 Finished majority of social page. May need some finishing touches
  mm-api/models/recap.js
  mm-api/models/social.js
  mm-api/routes/social.js
  motivateme-ui/services/apiclient.js
  motivateme-ui/src/components/GraphCard/GraphCard.css
  motivateme-ui/src/components/GraphCard/GraphCard.jsx
  motivateme-ui/src/components/RecapPage/RecapPage.css
  motivateme-ui/src/components/RecapPage/RecapPage.jsx
  motivateme-ui/src/components/SocialPage/SocialPage.css
  motivateme-ui/src/components/SocialPage/SocialPage.jsx
Labels: enhancement

#93 fixed error and added message if user has no upcoming tasks
  motivateme-ui/src/components/TodoForm/TodoForm.jsx
  motivateme-ui/src/components/TodoList/TodoList.css
  motivateme-ui/src/components/TodoList/TodoList.jsx
Labels: bug, enhancement

#94 Added message for no graphs and cleaned up code in file
  motivateme-ui/src/components/RecapPage/RecapPage.jsx
  motivateme-ui/src/components/RegisterPage/RegisterPage.css
Labels: enhancement

#95 Addrecommendedbox
  motivateme-ui/src/components/SocialPage/SocialPage.css
  motivateme-ui/src/components/SocialPage/SocialPage.jsx
Labels: enhancement

#96 Added recommended endpoint and updated API Client.
  mm-api/models/social.js
  mm-api/routes/social.js
  motivateme-ui/services/apiclient.js
Labels: enhancement

#98 Finished the social media page.
  mm-api/models/social.js
  motivateme-ui/src/components/SocialPage/SocialPage.css
  motivateme-ui/src/components/SocialPage/SocialPage.jsx
Labels: enhancement

#100 Added latest grade endpoint
  mm-api/models/recap.js
  mm-api/routes/recap.js
  mm-api/routes/social.js
  mm-api/routes/todo.js
  motivateme-ui/services/apiclient.js
Labels: enhancement

#101 Todo page #61
  motivateme-ui/README.md
  motivateme-ui/package-lock.json
  motivateme-ui/package.json
  motivateme-ui/src/assets/Exam Grade.svg
  motivateme-ui/src/components/DashboardPage/DashboardPage.css
  motivateme-ui/src/components/DashboardPage/DashboardPage.jsx
  motivateme-ui/src/components/GraphCard/GraphCard.css
  motivateme-ui/src/components/GraphCard/GraphCard.jsx
  motivateme-ui/src/main.jsx
Labels: enhancement

#107 Google Authentication Implemented
  mm-api/README.md
  mm-api/models/user.js
  mm-api/motivateme-schema.sql
  mm-api/package.json
  mm-api/routes/auth.js
  motivateme-ui/.env
  motivateme-ui/README.md
  motivateme-ui/package-lock.json
  motivateme-ui/package.json
  motivateme-ui/services/apiclient.js
  motivateme-ui/src/components/App/App.jsx
  motivateme-ui/src/components/LoginPage/LoginPage.css
  motivateme-ui/src/components/LoginPage/LoginPage.jsx
  motivateme-ui/src/components/Navbar/Navbar.jsx
  motivateme-ui/src/components/RegisterPage/RegisterPage.jsx
  motivateme-ui/vite.config.js
Labels: enhancement

#108 Added load more functionality
  motivateme-ui/src/components/Navbar/Navbar.css
  motivateme-ui/src/components/Navbar/Navbar.jsx
  motivateme-ui/src/components/RecapPage/RecapPage.css
  motivateme-ui/src/components/RecapPage/RecapPage.jsx
  motivateme-ui/src/components/SocialPage/SocialPage.css
Labels: enhancement

#111 added extra styling
  mm-api/routes/social.js
  mm-api/routes/todo.js
  motivateme-ui/src/components/DashboardPage/DashboardPage.css
  motivateme-ui/src/components/DashboardPage/DashboardPage.jsx
  motivateme-ui/src/components/GraphCard/GraphCard.css
  motivateme-ui/src/index.css
Labels: enhancement

#113 changed the css to match to the all the tabs
  motivateme-ui/package-lock.json
  motivateme-ui/src/components/DashboardPage/DashboardPage.css
  motivateme-ui/src/components/GraphCard/GraphCard.css
  motivateme-ui/src/components/SocialPage/SocialPage.css
  motivateme-ui/src/components/TodoList/TodoList.css
Labels: documentation

#114 Fixed formatting for buttons in SocialPage.jsx
  motivateme-ui/src/components/SocialPage/SocialPage.css
  motivateme-ui/src/components/SocialPage/SocialPage.jsx
Labels: bug

#116 Resized, formatted, and messages for dashboard
  motivateme-ui/src/components/DashboardPage/DashboardPage.css
  motivateme-ui/src/components/DashboardPage/DashboardPage.jsx
Labels: enhancement

#118 Todo page update #109
  motivateme-ui/src/assets/greenstatus-icon.png
  motivateme-ui/src/assets/ontime-icon-2.png
  motivateme-ui/src/assets/ontime-icon-3.jpg
  motivateme-ui/src/assets/ontime-icon.webp
  motivateme-ui/src/components/SocialPage/SocialPage.css
  motivateme-ui/src/components/TodoForm/TodoForm.css
  motivateme-ui/src/components/TodoList/TodoList.css
  motivateme-ui/src/components/TodoList/TodoList.jsx
  motivateme-ui/src/components/TodoPage/TodoPage.css
  motivateme-ui/src/components/TodoPage/TodoPage.jsx
  motivateme-ui/src/index.css
Labels: enhancement

#120 Google login #104
  motivateme-ui/src/assets/google-icon.webp
  motivateme-ui/src/components/LoginPage/LoginPage.css
  motivateme-ui/src/components/LoginPage/LoginPage.jsx
  motivateme-ui/src/components/Navbar/Navbar.css
  motivateme-ui/src/components/Navbar/Navbar.jsx
Labels: enhancement

#119 Profile Update Changes Endpoints
  mm-api/models/todo.js
  mm-api/models/user.js
  mm-api/routes/auth.js
  motivateme-ui/services/apiclient.js
Labels: enhancement

#125 fixed username and name in social page, adjusted css
  motivateme-ui/src/components/LoginPage/LoginPage.css
  motivateme-ui/src/components/RegisterPage/RegisterPage.css
  motivateme-ui/src/components/SocialPage/SocialPage.css
  motivateme-ui/src/components/SocialPage/SocialPage.jsx
Labels: documentation

#124 Can update profile and password now
  mm-api/models/user.js
  motivateme-ui/services/apiclient.js
  motivateme-ui/src/assets/lock-password.png
  motivateme-ui/src/components/App/App.jsx
  motivateme-ui/src/components/Navbar/Navbar.jsx
  motivateme-ui/src/components/ProfilePage/ProfilePage.css
  motivateme-ui/src/components/ProfilePage/ProfilePage.jsx
  motivateme-ui/src/components/SecurityChange/SecurityChange.css
  motivateme-ui/src/components/SecurityChange/SecurityChange.jsx
Labels: enhancement

#126 Fixed button and password error
  mm-api/models/user.js
  motivateme-ui/src/components/SocialPage/SocialPage.css
Labels: bug
